SRCS = \
  src/ChildLock.cpp \
  src/CommandMenuNode.cpp \
  src/MainMenuItemsProvider.cpp \
  src/MenuConfigurationRepository.cpp \
  src/MenuNode.cpp \
  src/MenuOrgPlugin.cpp \
  src/OsdItemDefinition.cpp \
  src/PluginConfiguration.cpp \
  src/PluginCreator.cpp \
  src/PluginItemDefinition.cpp \
  src/PluginMenuNode.cpp \
  src/PluginSetup.cpp \
  src/SubMenuNode.cpp \
  src/SystemMenuNode.cpp \
  src/i18n.cpp \
  src/OsdLineItem.cpp \
  src/SeparatorMenuNode.cpp \
  src/XmlConfigurationFactory.cpp \
  src/VdrState.cpp \
  src/MenuItemDefinitionFactory.cpp \
