SRCS = \
  src/ChildLock.cpp \
  src/CommandMenuNode.cpp \
  src/MainMenuItemsProvider.cpp \
  src/MenuConfigurationRepository.cpp \
  src/MenuNode.cpp \
  src/MenuOrgPlugin.cpp \
  src/OsdItemDefinition.cpp \
  src/PluginConfiguration.cpp \
  src/PluginCreator.cpp \
  src/PluginItemDefinition.cpp \
  src/PluginMenuNode.cpp \
  src/PluginSetup.cpp \
  src/RecursiveMenuSetup.cpp \
  src/SubMenuNode.cpp \
  src/SystemMenuNode.cpp \
  src/i18n.cpp \
  src/FlatMenuSetup.cpp \
  src/MenuItemSetup.cpp \
  src/OsdXmlItem.cpp \
  src/OsdLineItem.cpp \
  src/SeparatorMenuNode.cpp \
  src/XmlConfigurationFactory.cpp \
  src/VdrState.cpp \
  src/MenuItemDefinitionFactory.cpp \
  src/MenuSetupItemsFactory.cpp \
  src/MenuEditMenusFactory.cpp \
  src/CommandItemSetup.cpp \
  src/PluginItemSetup.cpp \
  src/SeparatorItemSetup.cpp \
  src/SystemItemSetup.cpp \
  src/SubMenuItemSetup.cpp \
